sudo: required
services:
 - docker

before_install:
 - docker build -t gpremk/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true gpremk/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "gpremk-docker-react"
 env: "Gpremkdockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-236969551149"
 bucket_path: "gpremk-docker-react"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"